apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-summary-config
  labels:
    app: todo-summary
    tier: backend
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8081" 
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health"  

