apiVersion: v1
kind: Secret
metadata:
  name: todo-summary-secret
  labels:
    app: todo-summary
    tier: backend
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/todo_db?createDatabaseIfNotExist=true
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: tiger
  COHERE_API_KEY: <your-cohere-api-key>
  SLACK_WEBHOOK_URL: https://hooks.slack.com/services/YOUR/WEBHOOK/URL  
   

