apiVersion: v1
kind: Service
metadata:
  name: todo-summary-service
  labels:
    app: todo-summary
    tier: backend
spec:
  type: NodePort
  selector:
    app: todo-summary
    tier: backend
  ports:
    - port: 80
      targetPort: 8081
      nodePort: 30007

